services:
  php:
    container_name: devkrylasovaru-php
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      VIRTUAL_HOST: dev.krylasova.local
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: devkrylasova
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      FRONTEND_URL: https://dev.krylasova.local
      SENTRY_DSN: https://6616c274402d464fad3deb3ccd34c2ab@o733117.ingest.sentry.io/5784548

  node:
    depends_on:
      - php
    container_name: devkrylasovaru-node
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - 80
    tty: true
    environment:
      VIRTUAL_HOST: node.krylasova.local

  mysql:
    image: mysql:5.7.27
    container_name: devkrylasovaru-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devkrylasova
    ports:
      - 33061:3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: devkrylasovaru-nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      VIRTUAL_HOST: dev.krylasova.local,node.krylasova.local

  mailer:
    image: mailhog/mailhog
    container_name: devkrylasovaru-mailer
    ports:
      - 8025:8025
