services:
  php-apache:
    container_name: ${COMPOSE_PROJECT_NAME}-php-apache
    build:
      context: docker/php-apache
    volumes:
      - ..:/var/www/html
    environment:
      VIRTUAL_HOST: dev.krylasova.local
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: devkrylasova
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      FRONTEND_URL: https://dev.krylasova.local
      SENTRY_DSN: https://6616c274402d464fad3deb3ccd34c2ab@o733117.ingest.sentry.io/5784548

  node:
    container_name: ${COMPOSE_PROJECT_NAME}-node
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../frontend:/home/node/app
      - ../public/assets:/home/node/app/dist/assets
      - ../templates:/home/node/app/dist/templates
    expose:
      - 80
    tty: true
    environment:
      VIRTUAL_HOST: node.krylasova.local

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devkrylasova
    ports:
      - 33061:3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  nginx-proxy:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      VIRTUAL_HOST: dev.krylasova.local,node.krylasova.local

  mailer:
    container_name: ${COMPOSE_PROJECT_NAME}-mailer
    image: mailhog/mailhog
    ports:
      - 8025:8025
