services:

  api:
    container_name: devkrylasovaru-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "8"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
    volumes:
        - /home/sergeev/www/dev.krylasova.ru:/var/www/html
        - /var/lib/docker/volumes/vscode/_data:/vscode
    environment:
      VIRTUAL_HOST: dev.krylasova.local
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: devkrylasova

  mysql:
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devkrylasova
    ports:
      - 33061:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: devkrylasovaru-nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      VIRTUAL_HOST: dev.krylasova.local
